name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/setup-monorepo

            - name: Lint
              run: bun run check

    build-and-test:
        name: Build and test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/setup-monorepo

            - name: Build
              run: bun run build

            - name: Test (core)
              run: bun test
              working-directory: package

            - name: Test (webpack loader)
              run: bun test
              working-directory: plugins/webpack

            - name: Test (CLI)
              run: bun test
              working-directory: cli

            - name: Test (Vite plugin)
              run: bun test
              working-directory: plugins/vite

            - name: Test (esbuild plugin)
              run: bun test
              working-directory: plugins/esbuild
